# 当master有代码提交或者有pr时，自动build gitbook，并覆盖git@github.com:zeromicro/go-zero.git仓库中内容
# 以实现自动发布文档

name: Document Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: chmod contributor tool
        run: chmod +x ./.github/workflows/contributor-tool
      - name: get latest contributors(zh)
        run: ./.github/workflows/contributor-tool -f contributor -l zh -o ./zh-hans/contributor.md
      - name: get latest contributors(en)
        run: ./.github/workflows/contributor-tool -f contributor -l en -o ./en/contributor.md
      - name: append gitalk
        run: ./.github/workflows/contributor-tool -f comment
      - name: use node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.1'
      - name: install gitbook
        run: npm install gitbook-cli -g
      - name: gitbook version
        run: gitbook --version
      - name: gitbook install
        run: gitbook install
      - name: build
        run: gitbook build
      - name: chmod
        run: chmod +x ./.github/workflows/build.sh
      - name: publish
        run: ./.github/workflows/build.sh ${{ secrets.ACCESSTOKEN }}
        shell: bash
